# Generated by Django 2.2 on 2019-05-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='moder',
            field=models.BooleanField(default=False, verbose_name='Модерация'),
        ),
        migrations.AddField(
            model_name='post',
            name='moder',
            field=models.BooleanField(default=False, verbose_name='Модерация'),
        ),
    ]
