# Generated by Django 2.2 on 2019-05-29 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190529_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterModelOptions(
            name='useraccount',
            options={'permissions': (('can_delete', 'can_create'),)},
        ),
    ]
